kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .RoleAndRolebindingName }}
  namespace: {{ .ClusterName }}
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows/status"]
    verbs: ["update", "patch"]
